### ISSUE TITLE
Questions about downloading dataset.

### ISSUE THREAD

**Issue by jinyuan30** [Diyago/ML-DL-scripts#3]
You wrote an excellent script to download dataset, thank you very much!
But there is a question when I run this script.

The progress sometimes show:HTTP Error 500. Therefore, I can't download the full data from this website, and when I locate the specific link that shown error, the chrome also shown HTTP Error 500, I don't know whether is my internet problem.

I don't know whether other guys have the same problem, could you offer an Google Drive link to download full dataset?

Thank you very much

**Comment by jinyuan30** [comment]
The project is road segmentation by the way.

**Comment by Diyago** [comment]
@jinyuan30  sure, I will upload dataset to Kaggle. Is it okay?

**Comment by jinyuan30** [comment]
> @jinyuan30 sure, I will upload dataset to Kaggle. Is it okay?

Kaggle is OK，Thank You！

**Comment by jinyuan30** [comment]
Excuse me?
There is another question.
When I finish the first epoch, and train window shows 276/277

There is a error "“”TypeError: 'bool' object is not callable“”“
Here is details:
`TypeError                                 Traceback (most recent call last)
<ipython-input-6-7ca8bb34a6a3> in <module>
     23                   epochs=50, workers=0, use_multiprocessing=True,
     24                   validation_data = test_generator,
---> 25                   verbose = 1) #callbacks=callbacks)
     26 #plotting history
     27 plot_training_history(history)

~\Anaconda3\envs\pytorch\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\Anaconda3\envs\pytorch\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1656             use_multiprocessing=use_multiprocessing,
   1657             shuffle=shuffle,
-> 1658             initial_epoch=initial_epoch)
   1659 
   1660     @interfaces.legacy_generator_methods_support

~\Anaconda3\envs\pytorch\lib\site-packages\keras\engine\training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    235                             validation_steps,
    236                             callbacks=callbacks,
--> 237                             workers=0)
    238                     else:
    239                         # No need for try/except because

~\Anaconda3\envs\pytorch\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\Anaconda3\envs\pytorch\lib\site-packages\keras\engine\training.py in evaluate_generator(self, generator, steps, callbacks, max_queue_size, workers, use_multiprocessing, verbose)
   1715             workers=workers,
   1716             use_multiprocessing=use_multiprocessing,
-> 1717             verbose=verbose)
   1718 
   1719     @interfaces.legacy_generator_methods_support

~\Anaconda3\envs\pytorch\lib\site-packages\keras\engine\training_generator.py in evaluate_generator(model, generator, steps, callbacks, max_queue_size, workers, use_multiprocessing, verbose)
    349 
    350         while steps_done < steps:
--> 351             generator_output = next(output_generator)
    352             if not hasattr(generator_output, '__len__'):
    353                 raise ValueError('Output of generator should be a tuple '

~\Anaconda3\envs\pytorch\lib\site-packages\keras\engine\training_utils.py in iter_sequence_infinite(seq)
    618     """
    619     while True:
--> 620         for item in seq:
    621             yield item
    622 

~\Anaconda3\envs\pytorch\lib\site-packages\keras\utils\data_utils.py in __iter__(self)
    375     def __iter__(self):
    376         """Create a generator that iterate over the Sequence."""
--> 377         for item in (self[i] for i in range(len(self))):
    378             yield item
    379 

~\Anaconda3\envs\pytorch\lib\site-packages\keras\utils\data_utils.py in <genexpr>(.0)
    375     def __iter__(self):
    376         """Create a generator that iterate over the Sequence."""
--> 377         for item in (self[i] for i in range(len(self))):
    378             yield item
    379 

<ipython-input-1-c0648b891d3a> in __getitem__(self, index)
     75 
     76                 # Augmentation code
---> 77                 augmented = self.augmentation(self.image_size)(image=X_sample, mask=y_sample)
     78                 image_augm = augmented['image']
     79                 mask_augm = augmented['mask'].reshape(self.image_size, self.image_size, self.nb_y_features)

TypeError: 'bool' object is not callable`

I think maybe the augmentation function had some problems? But I don't know how to change this part.

**Comment by Diyago** [comment]
https://www.kaggle.com/insaff/massachusetts-roads-dataset link to dataset

**Comment by Diyago** [comment]
I think there is something wrong  with your validation datagenerator, try to use method __getitem__ first

**Comment by jinyuan30** [comment]
Hi, thank you upload dataset on Kaggle.
I've run the code from beginning to end, and I debug details.
Here they are:

- Didn't define `listdir_fullpath`function, and one need import numpy.

- When define `test_generator`,  one should set `augmentation` as `aug_with_crop`  instead of False.

- In the Adding TTA part, I think this part lack of  `tta_model.compile` , one should type it on.

- Finally, in the testing part, one should change reshape size from 1478*1478 to 768*768, cause 1478 is mismatching. 

The above is the problem I encountered, you can modify it as appropriate

Thank you for the excellent tutorial！I've learned a lot from it!
