### ISSUE TITLE
segmentation pipeline training error

### ISSUE THREAD

**Issue by panovr** [Diyago/ML-DL-scripts#7]
```
Traceback (most recent call last):
  File ".\train.py", line 250, in <module>
    predicted = model.predict(np.expand_dims(Xtest[0], axis=0)).reshape(1472, 1472)
ValueError: cannot reshape array of size 589824 into shape (1472,1472)
```

May I ask why reshape to (1472, 1472)?

And, may you supply a separate predict.py for loading trained model and predict a test image?
Thanks!

**Comment by Diyago** [comment]
it was the image`s shape used in the competition. You may use any other image size.

**Comment by Diyago** [comment]
For inference take a look at https://github.com/Diyago/ML-DL-scripts/blob/master/DEEP%20LEARNING/segmentation/Severstal-Steel-Defect-Detection-master/inference.py
